namespace: ais-edge

pvcName: ais-edge
storageClassName: hostpath-pipeline

storageClass:
  create: true

storage:
  hostPath: /data/ais-edge
  capacity: 1500Gi

orthanc:
  image: jodogne/orthanc-plugins:1.12.11
  imagePullPolicy: IfNotPresent
  aet: ORTHANC
  authenticationEnabled: true
  dicomPort: 4242
  httpPort: 8042
  nodePorts:
    dicom: 30042
    http: 30842
  ingestTranscoding: "1.2.840.10008.1.2.1"
  dicomScuTimeout: 60
  plugins:
    - /usr/local/share/orthanc/plugins/libOrthancExplorer2.so
    - /usr/local/share/orthanc/plugins/libStoneWebViewer.so
    - /usr/local/share/orthanc/plugins/libOrthancDicomWeb.so
    - /usr/local/share/orthanc/plugins/libOrthancGdcm.so
  podSecurityContext:
    fsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
  securityContext:
    capabilities:
      drop:
        - ALL
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 2Gi
      cpu: "1"

samba:
  image: dockurr/samba:4.23.5
  shareName: edge
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

xnatIngest:
  image: ghcr.io/australian-imaging-service/xnat-ingest:0.12.3
  imagePullPolicy: IfNotPresent
  delete: "0"
  deidentify: "0"
  spacesToUnderscores: "0"

  dicomTagMapping:
    project: StudyDescription
    subject: PatientName
    sessionLabel: PatientID
    sessionUid: StudyInstanceUID
    scanDesc: SeriesDescription

  orthancIngest:
    enabled: true
    interval: 300
    processedLabel: xnat-sorted
    copyMode: hardlink_or_copy
    loggers: "stream info stdout;file debug /data/LOGS/xnat-ingest-orthanc.log"

  fsIngest:
    enabled: true
    interval: 300
    inputGlob: "/data/incoming/**/*"
    waitPeriod: 60
    datatypes: "medimage/dicom-series"
    copyMode: hardlink_or_copy
    loggers: "stream info stdout;file debug /data/LOGS/xnat-ingest-fs.log"

  upload:
    enabled: true
    replicas: 1
    alwaysInclude: "all"
    verifySsl: "1"
    useCurlJsession: "0"
    requireManifest: "0"
    checkChecksums: "0"
    loop: 300
    waitPeriod: 60
    tempdir: /data/tmp
    loggers: "stream debug stdout;file debug /data/LOGS/xnat-ingest-upload.log"

  associate:
    datatypes: "medimage/vnd.siemens.syngo-mr.xa.twix;medimage/vnd.siemens.syngo-mr.xa.rda;medimage/vnd.siemens.syngo-mr.xa.puls"
    copyMode: hardlink_or_copy
    loggers: "stream info stdout;file debug /data/LOGS/xnat-ingest-associate.log"
