apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-admin
    namespace: ais-mgmt
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:9Mgsp0i3WGsP57oUL3miOGgIRiY=,iv:0UedBVcyNdCmsI2oYbR/6h/40cmNu6tSfBkpBp011EY=,tag:Xb03sjIAmfDhsCnQcs8P1w==,type:str]
    secret-key: ENC[AES256_GCM,data:K1AcwyFULJtKUscGZSmdpglw31ITMVdrf6UNf5sRXCk=,iv:+ZvWwsgXTkvwQDI9L72Z8lf/JrL9EBtEZeuM/qKL0Qs=,tag:u8pvUM3kkBF9OiizZV4iYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaEJYcTh5V2MwWHYyVThw
            T2FQa2QyeFRiYkprbVE2eFVqckc5WUNjVEdrCmk2eG91bTRxeUNDT2ZaNUxLOExT
            UGw1OVZYZlQzbkh4OFBRNTFQZ0wrQkEKLS0tIDNxN0tjanh5RFp6S0NmUlFKekZo
            d09EKzdjZFFZWjR1eGd5dStzWG81QUEKIJNKXONUgEKqOT6jjaruPVJTI8kwAidY
            08+fpWeUqggVxJJqMjQsgkeVvamUQoGZiqVyGAs0aETeQuXdiSaB0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13952y4twf97ng8zjr654g496p6t9ud20hps5rwnwg0n0e2hmhvasr9w0nu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T01:49:05Z"
    mac: ENC[AES256_GCM,data:y2M8ba9kTR8BiJ3hIGN6Z+bAZJv4NlvbrxC+iZIktqZUSA+nRey2PU6/N0EmO5xvFJfD3BmvA9aQSMem/ulguJC0hc/Q+s4SI3HMzPMtW0oN1mmkp3eMd8wNt/FBbnBP2TnreJgYSfRfEURyurmjaITpApA8bmGL7h/COZBiQV0=,iv:o6eAVNPoExuQrsRBrMZMis1dQk3l/IgBsw1Icy4bAgY=,tag:lIMyB7NLJSmjTQuUsEeGqA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-upload
    namespace: xnat-upload
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:eEVXhY5Jres79IiFsxF2BYuVuZw=,iv:JHi7v9KOIhDOyDRbwgoyjTZFDXA6RpWQqKgaB6pTowU=,tag:WFmU2xcrMhywL+f4tCu7lw==,type:str]
    secret-key: ENC[AES256_GCM,data:VKxF5KQ0IpTF6IS1SOkU+D8c0PHzHsGDmeVW+4I1f2Y=,iv:qTHKio2a44OPMtX7l849fBb3VKGkBk+uJWjcpOLb15Y=,tag:GiK0oeBgHNbLSbw7huXtkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaEJYcTh5V2MwWHYyVThw
            T2FQa2QyeFRiYkprbVE2eFVqckc5WUNjVEdrCmk2eG91bTRxeUNDT2ZaNUxLOExT
            UGw1OVZYZlQzbkh4OFBRNTFQZ0wrQkEKLS0tIDNxN0tjanh5RFp6S0NmUlFKekZo
            d09EKzdjZFFZWjR1eGd5dStzWG81QUEKIJNKXONUgEKqOT6jjaruPVJTI8kwAidY
            08+fpWeUqggVxJJqMjQsgkeVvamUQoGZiqVyGAs0aETeQuXdiSaB0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13952y4twf97ng8zjr654g496p6t9ud20hps5rwnwg0n0e2hmhvasr9w0nu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T01:49:05Z"
    mac: ENC[AES256_GCM,data:y2M8ba9kTR8BiJ3hIGN6Z+bAZJv4NlvbrxC+iZIktqZUSA+nRey2PU6/N0EmO5xvFJfD3BmvA9aQSMem/ulguJC0hc/Q+s4SI3HMzPMtW0oN1mmkp3eMd8wNt/FBbnBP2TnreJgYSfRfEURyurmjaITpApA8bmGL7h/COZBiQV0=,iv:o6eAVNPoExuQrsRBrMZMis1dQk3l/IgBsw1Icy4bAgY=,tag:lIMyB7NLJSmjTQuUsEeGqA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-upload
    namespace: ais-mgmt
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:SFwSywe9zo7cpnpM7XlE3zEXi08=,iv:jlJdSmv+Y8kxZUfP6pIaZvNJbfahxI5qittgRZe3gfs=,tag:sEPPBTtfg9TRqAgRhcvGLw==,type:str]
    secret-key: ENC[AES256_GCM,data:POk1xTkpVYJ9s17WGlOkwcZxUqVs1sRQiI+zqW1RPNA=,iv:V53LmpFz6CJAD+BfuE5SP4VpN/nAeZHkvlIZ9m7z9o8=,tag:ceGnKmzBI9yhmP5LbIbq7Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaEJYcTh5V2MwWHYyVThw
            T2FQa2QyeFRiYkprbVE2eFVqckc5WUNjVEdrCmk2eG91bTRxeUNDT2ZaNUxLOExT
            UGw1OVZYZlQzbkh4OFBRNTFQZ0wrQkEKLS0tIDNxN0tjanh5RFp6S0NmUlFKekZo
            d09EKzdjZFFZWjR1eGd5dStzWG81QUEKIJNKXONUgEKqOT6jjaruPVJTI8kwAidY
            08+fpWeUqggVxJJqMjQsgkeVvamUQoGZiqVyGAs0aETeQuXdiSaB0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13952y4twf97ng8zjr654g496p6t9ud20hps5rwnwg0n0e2hmhvasr9w0nu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T01:49:05Z"
    mac: ENC[AES256_GCM,data:y2M8ba9kTR8BiJ3hIGN6Z+bAZJv4NlvbrxC+iZIktqZUSA+nRey2PU6/N0EmO5xvFJfD3BmvA9aQSMem/ulguJC0hc/Q+s4SI3HMzPMtW0oN1mmkp3eMd8wNt/FBbnBP2TnreJgYSfRfEURyurmjaITpApA8bmGL7h/COZBiQV0=,iv:o6eAVNPoExuQrsRBrMZMis1dQk3l/IgBsw1Icy4bAgY=,tag:lIMyB7NLJSmjTQuUsEeGqA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: xnat-credentials
    namespace: xnat-upload
type: Opaque
stringData:
    server: ENC[AES256_GCM,data:ekv8RVY4/OTEMU01YWkMutv0Wg7m4SbNqFfF1hKlTNtN71BzVzo=,iv:hPzxCQD8CjAwSruANqlRRZKxqLqDj/DKRSHQxdxE1+A=,tag:x/sKeGR0kLQOBFwvfaXKxg==,type:str]
    username: ENC[AES256_GCM,data:Y+SwIQg=,iv:ERo4SYcHzIvNlKij7OJeSlIwAJMaSk88uVwTSMvsJZg=,tag:LOX9KyUapOVhysjW9aAj3w==,type:str]
    password: ENC[AES256_GCM,data:K0Q8kPY=,iv:02dzx77XNN1IFC5G84cPeCyH/liepx8VO7ZwxAeQoRI=,tag:AjCYcu+wjgGZuIiDwylp5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaEJYcTh5V2MwWHYyVThw
            T2FQa2QyeFRiYkprbVE2eFVqckc5WUNjVEdrCmk2eG91bTRxeUNDT2ZaNUxLOExT
            UGw1OVZYZlQzbkh4OFBRNTFQZ0wrQkEKLS0tIDNxN0tjanh5RFp6S0NmUlFKekZo
            d09EKzdjZFFZWjR1eGd5dStzWG81QUEKIJNKXONUgEKqOT6jjaruPVJTI8kwAidY
            08+fpWeUqggVxJJqMjQsgkeVvamUQoGZiqVyGAs0aETeQuXdiSaB0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13952y4twf97ng8zjr654g496p6t9ud20hps5rwnwg0n0e2hmhvasr9w0nu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T01:49:05Z"
    mac: ENC[AES256_GCM,data:y2M8ba9kTR8BiJ3hIGN6Z+bAZJv4NlvbrxC+iZIktqZUSA+nRey2PU6/N0EmO5xvFJfD3BmvA9aQSMem/ulguJC0hc/Q+s4SI3HMzPMtW0oN1mmkp3eMd8wNt/FBbnBP2TnreJgYSfRfEURyurmjaITpApA8bmGL7h/COZBiQV0=,iv:o6eAVNPoExuQrsRBrMZMis1dQk3l/IgBsw1Icy4bAgY=,tag:lIMyB7NLJSmjTQuUsEeGqA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: ais-mgmt
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:7j1RhbY=,iv:sCaR/9/LL1beL21yYZcmdrkMV00xUcIv+nqKoN3+L4M=,tag:xpr+XBgHB+Ce5Gg7Y5OOMA==,type:str]
    admin-password: ENC[AES256_GCM,data:cqREzlNRrQ5F/UdmVKGhyrYuWXe+hZDkfozZf3yCNAo=,iv:qoRrZYgg5YbNLbRb3b5Z8VkBY3phHehuqrQyT7ClmcU=,tag:60yJ/NDuQW/0pl6x+UBbVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaEJYcTh5V2MwWHYyVThw
            T2FQa2QyeFRiYkprbVE2eFVqckc5WUNjVEdrCmk2eG91bTRxeUNDT2ZaNUxLOExT
            UGw1OVZYZlQzbkh4OFBRNTFQZ0wrQkEKLS0tIDNxN0tjanh5RFp6S0NmUlFKekZo
            d09EKzdjZFFZWjR1eGd5dStzWG81QUEKIJNKXONUgEKqOT6jjaruPVJTI8kwAidY
            08+fpWeUqggVxJJqMjQsgkeVvamUQoGZiqVyGAs0aETeQuXdiSaB0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13952y4twf97ng8zjr654g496p6t9ud20hps5rwnwg0n0e2hmhvasr9w0nu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T01:49:05Z"
    mac: ENC[AES256_GCM,data:y2M8ba9kTR8BiJ3hIGN6Z+bAZJv4NlvbrxC+iZIktqZUSA+nRey2PU6/N0EmO5xvFJfD3BmvA9aQSMem/ulguJC0hc/Q+s4SI3HMzPMtW0oN1mmkp3eMd8wNt/FBbnBP2TnreJgYSfRfEURyurmjaITpApA8bmGL7h/COZBiQV0=,iv:o6eAVNPoExuQrsRBrMZMis1dQk3l/IgBsw1Icy4bAgY=,tag:lIMyB7NLJSmjTQuUsEeGqA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: loki-s3-credentials
    namespace: ais-mgmt
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:KjrxgW66BfL4blQLSZdsLcu4QXY=,iv:OJBaLvi0ZF7Dqdx9lBeNK4RdePSq2GuFYSoAZZNrHYQ=,tag:T2VNBkDCe5MoXLLPo0159g==,type:str]
    secret-key: ENC[AES256_GCM,data:Elpz3M+iCmbP3p/DGd1ctw8QvzkTJgrq/z8ZyUnW4X4=,iv:bTJ6xpz7V17TNarPW7dWDJjktBdcwWejXa4NI3j7c7I=,tag:gHwWQ6v9sgAi3WgLIPll4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaEJYcTh5V2MwWHYyVThw
            T2FQa2QyeFRiYkprbVE2eFVqckc5WUNjVEdrCmk2eG91bTRxeUNDT2ZaNUxLOExT
            UGw1OVZYZlQzbkh4OFBRNTFQZ0wrQkEKLS0tIDNxN0tjanh5RFp6S0NmUlFKekZo
            d09EKzdjZFFZWjR1eGd5dStzWG81QUEKIJNKXONUgEKqOT6jjaruPVJTI8kwAidY
            08+fpWeUqggVxJJqMjQsgkeVvamUQoGZiqVyGAs0aETeQuXdiSaB0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13952y4twf97ng8zjr654g496p6t9ud20hps5rwnwg0n0e2hmhvasr9w0nu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T01:49:05Z"
    mac: ENC[AES256_GCM,data:y2M8ba9kTR8BiJ3hIGN6Z+bAZJv4NlvbrxC+iZIktqZUSA+nRey2PU6/N0EmO5xvFJfD3BmvA9aQSMem/ulguJC0hc/Q+s4SI3HMzPMtW0oN1mmkp3eMd8wNt/FBbnBP2TnreJgYSfRfEURyurmjaITpApA8bmGL7h/COZBiQV0=,iv:o6eAVNPoExuQrsRBrMZMis1dQk3l/IgBsw1Icy4bAgY=,tag:lIMyB7NLJSmjTQuUsEeGqA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-smtp
    namespace: ais-mgmt
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:FimDjbLBAT7WCKXSXPWReoI9tG+Z,iv:9biRMcmZp5Lp1xM6+7lbN19oDSk5djHPm719BS1tIXg=,tag:ujsLcayjwKc6kp/y4jmvOA==,type:str]
    password: ENC[AES256_GCM,data:pfDHmbnZqODqcH0/QrXsmA==,iv:gZbqSga1w8iU/4kaItSp8Gz3md8XDfrfoHx3RDqDHOM=,tag:iimZN3yQkk3wGJrVHmIQ1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaEJYcTh5V2MwWHYyVThw
            T2FQa2QyeFRiYkprbVE2eFVqckc5WUNjVEdrCmk2eG91bTRxeUNDT2ZaNUxLOExT
            UGw1OVZYZlQzbkh4OFBRNTFQZ0wrQkEKLS0tIDNxN0tjanh5RFp6S0NmUlFKekZo
            d09EKzdjZFFZWjR1eGd5dStzWG81QUEKIJNKXONUgEKqOT6jjaruPVJTI8kwAidY
            08+fpWeUqggVxJJqMjQsgkeVvamUQoGZiqVyGAs0aETeQuXdiSaB0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13952y4twf97ng8zjr654g496p6t9ud20hps5rwnwg0n0e2hmhvasr9w0nu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T01:49:05Z"
    mac: ENC[AES256_GCM,data:y2M8ba9kTR8BiJ3hIGN6Z+bAZJv4NlvbrxC+iZIktqZUSA+nRey2PU6/N0EmO5xvFJfD3BmvA9aQSMem/ulguJC0hc/Q+s4SI3HMzPMtW0oN1mmkp3eMd8wNt/FBbnBP2TnreJgYSfRfEURyurmjaITpApA8bmGL7h/COZBiQV0=,iv:o6eAVNPoExuQrsRBrMZMis1dQk3l/IgBsw1Icy4bAgY=,tag:lIMyB7NLJSmjTQuUsEeGqA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: cloud-edge-s3
    namespace: ais-mgmt
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:wNogXO9fXZ//geUTjE8uunjz0XY=,iv:MAceLy9KJaNEM+AG/+59S38fE58Rg3Hn6Zg8bR7ptac=,tag:/eEHMAH37FnP7qtmA9ZLFA==,type:str]
    secret-key: ENC[AES256_GCM,data:Ums1MqF/qoMVEFvkfTw5jhAZp6R42ZZ0mBpOUxDaaxA=,iv:Q6dJ31iTEJSJClckSvAkvlhxvm+CJAIy0rGdhFnIiFM=,tag:4ZvVmXlAM8w4eW3mwW3pew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaEJYcTh5V2MwWHYyVThw
            T2FQa2QyeFRiYkprbVE2eFVqckc5WUNjVEdrCmk2eG91bTRxeUNDT2ZaNUxLOExT
            UGw1OVZYZlQzbkh4OFBRNTFQZ0wrQkEKLS0tIDNxN0tjanh5RFp6S0NmUlFKekZo
            d09EKzdjZFFZWjR1eGd5dStzWG81QUEKIJNKXONUgEKqOT6jjaruPVJTI8kwAidY
            08+fpWeUqggVxJJqMjQsgkeVvamUQoGZiqVyGAs0aETeQuXdiSaB0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13952y4twf97ng8zjr654g496p6t9ud20hps5rwnwg0n0e2hmhvasr9w0nu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T01:49:05Z"
    mac: ENC[AES256_GCM,data:y2M8ba9kTR8BiJ3hIGN6Z+bAZJv4NlvbrxC+iZIktqZUSA+nRey2PU6/N0EmO5xvFJfD3BmvA9aQSMem/ulguJC0hc/Q+s4SI3HMzPMtW0oN1mmkp3eMd8wNt/FBbnBP2TnreJgYSfRfEURyurmjaITpApA8bmGL7h/COZBiQV0=,iv:o6eAVNPoExuQrsRBrMZMis1dQk3l/IgBsw1Icy4bAgY=,tag:lIMyB7NLJSmjTQuUsEeGqA==,type:str]
    version: 3.13.3
