apiVersion: v1
kind: ConfigMap
metadata:
  name: orthanc-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "edge.labels" . | nindent 4 }}
data:
  orthanc.json: |
    {
      "StorageDirectory": "/data",
      "DicomAet": {{ .Values.orthanc.aet | quote }},
      "DicomPort": {{ .Values.orthanc.dicomPort }},
      "HttpPort": {{ .Values.orthanc.httpPort }},
      "RemoteAccessAllowed": true,
      "AuthenticationEnabled": {{ .Values.orthanc.authenticationEnabled }},
      "Plugins": {{ .Values.orthanc.plugins | toJson }},
      "IngestTranscoding": {{ .Values.orthanc.ingestTranscoding | quote }},
      "DicomScuTimeout": {{ .Values.orthanc.dicomScuTimeout }},
      "OrthancExplorer2": {
        "UiOptions": {
          "EnableViewerQuickButton": true,
          "ViewersOrdering": ["stone-webviewer"]
        }
      }
    }
